[package]
name = "rustic-rs"
version = "0.2.2"
description = """
fast, encrypted, deduplicated backups powered by pure Rust
"""
authors = ["Alexander Weiss"]
edition = "2021"
license = "Apache-2.0 OR MIT"
readme = "README.md"
documentation = "https://docs.rs/rustic-rs"
repository = "https://github.com/rustic-rs/rustic"
keywords = ["backup", "restic", "deduplication", "encryption", "cli"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# macros
async-trait = "0.1"
anyhow = "1"
ambassador = "0.2"
thiserror = "1"
derive_more = "0.99"
derivative = "2"
derive-getters = "0.2"
lazy_static = "1"
vlog = "0.1"
# async
tokio = { version = "1", features = ["full"] }
futures = "0.3"
#crypto
aes256ctr_poly1305aes = "0.1"
sha2 = "0.10"
rand = "0.8"
scrypt = { version = "0.10", default-features = false }
# chunker / packer
cdc = "0.1"
integer-sqrt = "0.1"
# serialization
base64 = "0.13"
binrw = "0.9"
hex = { version = "0.4", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde-aux = "3"
# other dependencies
chrono = { version = "0.4", features = ["serde"] }
tempfile = "3"
zstd = "0.11"
enum-map = "2"
enum-map-derive = "0.9"
# local backend
walkdir = "2"
ignore = "0.4"
nix = "0.24"
filetime = "0.2"
# rest backend
reqwest = {version = "0.11", default-features = false, features = ["json", "rustls-tls", "stream"] }
# rclone backend
sha1 = "0.10"
# cache
dirs = "4"
cachedir = "0.3"
# commands
clap = { version = "3", features = ["derive"] }
rpassword = "6"
prettytable-rs = {version = "0.8", default-features = false }
bytesize = "1"
indicatif = "0.17.0-rc.10"
path-absolutize = "3"
gethostname = "0.2"
humantime = "2"
users = "0.11"
itertools = "0.10"
