on:
  workflow_call: 
    inputs:
      ref:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      ref:
        required: true
        type: string


jobs:

  check:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.early.status }}
    steps:
      - id: early
        run: |
          if [ -f Dockerfile ]; then
            echo "status=success" | tee /dev/stderr >> $GITHUB_OUTPUT
          else
            echo "status=failure" | tee /dev/stderr >> $GITHUB_OUTPUT
          fi

  docker:
    needs: check
    if: needs.check.outputs.status == 'success'

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - uses: docker/setup-qemu-action@v3 # Add support for more platforms with QEMU (optional)
      - uses: docker/setup-buildx-action@v3 # Driver that adds support for caches, multiplatform and more features
      # TODO: cosign
      - name: Login to registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: docker.io  # registry.hub.docker.com
          username: yeicor
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: RUST_VERSION=slim-bookworm
          platforms: linux/amd64  # ,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: docker.io/yeicor/rustic:${{ inputs.ref }}
          cache-from: type=gha
          cache-to: type=gha,mode=max