on:
  # schedule:
  #   - cron: '0 * * * *'
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - '.github/**'
  workflow_dispatch: {}


jobs:

  docker:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - registry: ghcr.io
            username: ${{ github.actor }}
            password_secret_name: GITHUB_TOKEN
            image_name: ${{ github.repository }}
          - registry: registry.hub.docker.com
            username: yeicor
            password_secret_name: DOCKERHUB_TOKEN
            image_name: Yeicor/rustic

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image_name }}
      - name: Login to registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ matrix.registry }}
          username: ${{ matrix.username }}
          password: ${{ secrets[matrix.password_secret_name] }}
      # TODO: cosign
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: RUST_VERSION=slim-bookworm
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}