on:
  # schedule:
  #   - cron: '0 * * * *'
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch: {}

jobs:
  mirror:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4  # Checkout original repository
        with:
          repository: 'rustic-rs/rustic'
          fetch-depth: 0
      - run: |
          find $(dirname ${GITHUB_WORKSPACE})
          mv ${GITHUB_WORKSPACE} ${GITHUB_WORKSPACE}_original
          mkdir ${GITHUB_WORKSPACE}
          echo "==========="
          find $(dirname ${GITHUB_WORKSPACE})
      - uses: actions/checkout@v4   # Checkout self (to keep our custom files)
        with:
          fetch-depth: 0
      - run: |  
          # Delete all non-custom files from our repository (in case of deletions in the original repository)
          find ${GITHUB_WORKSPACE}/ -type f -not \( -path "${GITHUB_WORKSPACE}/.git/*" -or -path "${GITHUB_WORKSPACE}/.github/workflows/yeicor-*" -or -path "${GITHUB_WORKSPACE}/renovate.json" \) -delete
          find ${GITHUB_WORKSPACE}/ -type d -empty -delete
          find ${GITHUB_WORKSPACE}/
          # Copy all files from the original repository
          rsync -a --exclude='.git' ${GITHUB_WORKSPACE}_original/ ${GITHUB_WORKSPACE}/
          git config --global user.name 'yeicor-mirror.yml'
          git config --global user.email 'Yeicor@users.noreply.github.com'
          git add -v .
          git commit -am "Automated sync of original sources"
          git push
          
      
          
