on:
  # schedule:
  #   - cron: '0 * * * *'
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch: {}

jobs:
  mirror:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4  # Checkout self (to keep our custom files)
        with:
          repository: 'rustic-rs/rustic'
          fetch-depth: 0
      - run: |
          find ${GITHUB_WORKSPACE}/..
          mv ${GITHUB_WORKSPACE} ${GITHUB_WORKSPACE}_old
          find ${GITHUB_WORKSPACE}/..
          find ${GITHUB_WORKSPACE}_old/ -type f -not \( -path "${GITHUB_WORKSPACE}_old/.github/workflows/yeicor-" -or -path "${GITHUB_WORKSPACE}_old/renovate.json" \) -delete
          find ${GITHUB_WORKSPACE}_old/ -type d -empty -delete
          find ${GITHUB_WORKSPACE}_old/
          mkdir ${GITHUB_WORKSPACE}
      - uses: actions/checkout@v4  # Checkout original repository
        with:
          repository: 'rustic-rs/rustic'
          fetch-depth: 0
      - run: |  # Overwrite the original repository with our files
          find ${GITHUB_WORKSPACE}_old/
          mv ${GITHUB_WORKSPACE}_old/* ${GITHUB_WORKSPACE}/
          git remote add mirror "git@github.com:${{ github.repository }}.git"
          git push --tags --force --prune mirror "refs/remotes/origin/*:refs/heads/*"
          
